import Quiz from '../../models/Quiz.js';
import Lesson from '../../models/Lesson.js';
import AppError from '../../utils/AppError.js';
import OpenAI from 'openai';

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

class QuizService {
  /**
   * Generate MCQ and subjective questions from lesson content
   * @param {string} lessonId - Lesson ID
   * @param {object} options - Generation options
   * @returns {object} Quiz with generated questions
   */
  static async generateQuizFromLesson(lessonId, options = {}) {
    const {
      mcqCount = 5,
      subjectiveCount = 3,
      difficulty = 'medium',
      courseId = null
    } = options;

    // Fetch lesson content
    const lesson = await Lesson.findById(lessonId).populate('course');
    if (!lesson) throw new AppError('Lesson not found', 404);

    const courseId_ = courseId || lesson.course._id;

    // Validate that lesson has content
    if (!lesson.content && !lesson.transcript) {
      throw new AppError('Lesson must have content or transcript to generate quiz', 400);
    }

    const lessonContent = lesson.content || lesson.transcript;

    // Generate both MCQ and subjective questions
    const [mcqQuestions, subjectiveQuestions] = await Promise.all([
      this.generateMCQQuestions(lessonContent, mcqCount, difficulty),
      this.generateSubjectiveQuestions(lessonContent, subjectiveCount, difficulty),
    ]);

    // Combine and shuffle all questions
    const allQuestions = [...mcqQuestions, ...subjectiveQuestions];
    
    // Assign order
    allQuestions.forEach((q, idx) => {
      q.order = idx;
    });

    // Create quiz document
    const quiz = new Quiz({
      lesson: lessonId,
      course: courseId_,
      title: `${lesson.title} - Quiz`,
      description: `Auto-generated quiz for ${lesson.title}`,
      questions: allQuestions,
      totalQuestions: allQuestions.length,
      mcqCount: mcqQuestions.length,
      subjectiveCount: subjectiveQuestions.length,
      generatedAt: new Date(),
      isAutoGenerated: true,
      isPublished: false,
    });

    await quiz.save();

    // Update lesson with quiz reference
    lesson.quizId = quiz._id;
    await lesson.save();

    return quiz;
  }

  /**
   * Generate MCQ questions using OpenAI
   * @private
   */
  static async generateMCQQuestions(content, count, difficulty) {
    const prompt = `You are an expert quiz creator. Based on the following lesson content, generate ${count} Multiple Choice Questions (MCQs) with difficulty level: ${difficulty}.

LESSON CONTENT:
${content.substring(0, 3000)}

Generate EXACTLY ${count} MCQ questions in the following JSON format:
[
  {
    "question": "Question text here?",
    "options": ["Option 1", "Option 2", "Option 3", "Option 4"],
    "correctOption": 0,
    "difficulty": "${difficulty}"
  }
]

Requirements:
- Each question must have exactly 4 options
- correctOption should be a number (0-3) indicating the correct answer
- Questions must be clear and based on the provided content
- Avoid duplicate or similar questions
- Make questions engaging and test understanding

Return ONLY valid JSON array, no additional text.`;

    try {
      const response = await openai.chat.completions.create({
        model: 'gpt-3.5-turbo',
        messages: [
          {
            role: 'system',
            content: 'You are a professional quiz creator. Always respond with valid JSON only.',
          },
          {
            role: 'user',
            content: prompt,
          },
        ],
        temperature: 0.7,
        max_tokens: 2000,
      });

      const responseText = response.choices[0].message.content;
      const cleanedResponse = responseText
        .replace(/```json\n?/g, '')
        .replace(/```\n?/g, '')
        .trim();

      const questions = JSON.parse(cleanedResponse);

      return questions.map((q) => ({
        type: 'mcq',
        question: q.question,
        options: q.options,
        correctOption: q.correctOption,
        difficulty: q.difficulty || difficulty,
      }));
    } catch (error) {
      console.error('Error generating MCQ questions:', error);
      throw new AppError('Failed to generate MCQ questions', 500);
    }
  }

  /**
   * Generate Subjective questions using OpenAI
   * @private
   */
  static async generateSubjectiveQuestions(content, count, difficulty) {
    const prompt = `You are an expert quiz creator. Based on the following lesson content, generate ${count} Subjective/Essay type questions with difficulty level: ${difficulty}.

LESSON CONTENT:
${content.substring(0, 3000)}

Generate EXACTLY ${count} subjective questions in the following JSON format:
[
  {
    "question": "Question text here?",
    "sampleAnswer": "A comprehensive answer that covers the key points...",
    "difficulty": "${difficulty}"
  }
]

Requirements:
- Questions should encourage critical thinking and detailed answers
- Sample answers should be concise but comprehensive (2-3 sentences)
- Questions must be based on the provided content
- Avoid duplicate or similar questions
- Make questions thought-provoking

Return ONLY valid JSON array, no additional text.`;

    try {
      const response = await openai.chat.completions.create({
        model: 'gpt-3.5-turbo',
        messages: [
          {
            role: 'system',
            content: 'You are a professional quiz creator. Always respond with valid JSON only.',
          },
          {
            role: 'user',
            content: prompt,
          },
        ],
        temperature: 0.7,
        max_tokens: 2000,
      });

      const responseText = response.choices[0].message.content;
      const cleanedResponse = responseText
        .replace(/```json\n?/g, '')
        .replace(/```\n?/g, '')
        .trim();

      const questions = JSON.parse(cleanedResponse);

      return questions.map((q) => ({
        type: 'subjective',
        question: q.question,
        sampleAnswer: q.sampleAnswer,
        difficulty: q.difficulty || difficulty,
      }));
    } catch (error) {
      console.error('Error generating subjective questions:', error);
      throw new AppError('Failed to generate subjective questions', 500);
    }
  }

  /**
   * Get quiz by ID
   */
  static async getQuizById(quizId) {
    const quiz = await Quiz.findById(quizId)
      .populate('lesson', 'title slug')
      .populate('course', 'title slug');

    if (!quiz) throw new AppError('Quiz not found', 404);
    return quiz;
  }

  /**
   * Get quiz by lesson ID
   */
  static async getQuizByLessonId(lessonId) {
    const quiz = await Quiz.findOne({ lesson: lessonId })
      .populate('lesson', 'title slug')
      .populate('course', 'title slug');

    if (!quiz) return null;
    return quiz;
  }

  /**
   * Update quiz settings
   */
  static async updateQuizSettings(quizId, updates) {
    const allowedFields = [
      'title',
      'description',
      'passingScore',
      'timeLimit',
      'allowRetake',
      'showAnswers',
      'randomizeQuestions',
      'randomizeOptions',
      'isPublished',
    ];

    const filteredUpdates = {};
    allowedFields.forEach((field) => {
      if (updates.hasOwnProperty(field)) {
        filteredUpdates[field] = updates[field];
      }
    });

    const quiz = await Quiz.findByIdAndUpdate(quizId, filteredUpdates, {
      new: true,
      runValidators: true,
    });

    if (!quiz) throw new AppError('Quiz not found', 404);
    return quiz;
  }

  /**
   * Regenerate questions for a quiz
   */
  static async regenerateQuestions(quizId, options = {}) {
    const quiz = await Quiz.findById(quizId);
    if (!quiz) throw new AppError('Quiz not found', 404);

    const lesson = await Lesson.findById(quiz.lesson);
    if (!lesson) throw new AppError('Lesson not found', 404);

    const mcqCount = options.mcqCount || quiz.mcqCount;
    const subjectiveCount = options.subjectiveCount || quiz.subjectiveCount;
    const difficulty = options.difficulty || 'medium';

    const lessonContent = lesson.content || lesson.transcript;

    // Generate new questions
    const [mcqQuestions, subjectiveQuestions] = await Promise.all([
      this.generateMCQQuestions(lessonContent, mcqCount, difficulty),
      this.generateSubjectiveQuestions(lessonContent, subjectiveCount, difficulty),
    ]);

    const allQuestions = [...mcqQuestions, ...subjectiveQuestions];
    allQuestions.forEach((q, idx) => {
      q.order = idx;
    });

    // Update quiz
    quiz.questions = allQuestions;
    quiz.totalQuestions = allQuestions.length;
    quiz.mcqCount = mcqQuestions.length;
    quiz.subjectiveCount = subjectiveQuestions.length;
    quiz.generatedAt = new Date();

    await quiz.save();
    return quiz;
  }

  /**
   * Delete quiz
   */
  static async deleteQuiz(quizId) {
    const quiz = await Quiz.findByIdAndDelete(quizId);
    if (!quiz) throw new AppError('Quiz not found', 404);

    // Remove quiz reference from lesson
    await Lesson.updateOne(
      { quizId },
      { $set: { quizId: null } }
    );

    return quiz;
  }
}

export default QuizService;
