import mongoose from 'mongoose';

/** Question schema within Quiz */
const questionSchema = new mongoose.Schema({
  type: { type: String, enum: ['mcq', 'subjective'], required: true },
  question: { type: String, required: true },
  
  // For MCQ only
  options: [{ type: String }],  // Array of 4 options
  correctOption: { type: Number }, // Index of correct option (0-3)
  
  // For subjective
  sampleAnswer: { type: String }, // Expected answer guidance
  
  order: { type: Number, default: 0 },
  difficulty: { type: String, enum: ['easy', 'medium', 'hard'], default: 'medium' },
}, { _id: true });

/** Quiz schema */
const quizSchema = new mongoose.Schema({
  lesson: { type: mongoose.Schema.Types.ObjectId, ref: 'Lesson', required: true, index: true },
  course: { type: mongoose.Schema.Types.ObjectId, ref: 'Course', required: true, index: true },
  title: { type: String, required: true },
  description: { type: String },
  
  // Questions array
  questions: { type: [questionSchema], default: [] },
  
  // Quiz metadata
  totalQuestions: { type: Number, default: 0 },
  mcqCount: { type: Number, default: 0 },
  subjectiveCount: { type: Number, default: 0 },
  
  // Quiz settings
  passingScore: { type: Number, default: 70 }, // Percentage
  timeLimit: { type: Number, default: 0 }, // 0 = no limit, in minutes
  allowRetake: { type: Boolean, default: true },
  showAnswers: { type: Boolean, default: true },
  randomizeQuestions: { type: Boolean, default: false },
  randomizeOptions: { type: Boolean, default: false },
  
  // AI Generation metadata
  generatedBy: { type: String, default: 'gpt-3.5-turbo' },
  generatedAt: { type: Date, default: null },
  isAutoGenerated: { type: Boolean, default: true },
  
  // Status
  isPublished: { type: Boolean, default: false },
  
}, { timestamps: true });

quizSchema.index({ lesson: 1 });
quizSchema.index({ course: 1 });

export default mongoose.model('Quiz', quizSchema);
